/*
Nombres: Israel Rios Contreras
Carrera: Ingenieria en informatica
Cuatrimestre: 5
Grupo:B
Evidencia: Integradora
EPI_POO2019_IsraelRios.
*/
package vista;

/**
 *
 * @author israel
 */
import java.util.ArrayList;
import java.util.TreeMap;
import java.util.TreeSet;
import modelo.*;
import controlador.Biblioteca;
public class Principal extends javax.swing.JFrame 
{
   
    public Principal() 
    {
        initComponents();
        if(Biblioteca.materiales==null&&Biblioteca.prestamos==null&&Biblioteca.usuarios==null)
        {
            Biblioteca.materiales=new ArrayList<Material>();
            Biblioteca.usuarios=new ArrayList<Usuario>();
            Biblioteca.prestamos=new ArrayList<Prestamo>();
            Biblioteca.inicializarPrestamos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_crud_libro = new javax.swing.JButton();
        btn_crud_prestamo_simple = new javax.swing.JButton();
        btn_mostrar_material = new javax.swing.JButton();
        btn_mostrar_prestamos = new javax.swing.JButton();
        btn_mostrar_usuarios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_crud_revista = new javax.swing.JButton();
        btn_crud_prestamo_profesor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnEditarPrestamo = new javax.swing.JButton();
        btnEliminarPrestamo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_crud_libro.setText("CRUD LIBRO");
        btn_crud_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crud_libroActionPerformed(evt);
            }
        });

        btn_crud_prestamo_simple.setText("Añadir Prestamo");
        btn_crud_prestamo_simple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crud_prestamo_simpleActionPerformed(evt);
            }
        });

        btn_mostrar_material.setText("Mostrar Material");
        btn_mostrar_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrar_materialActionPerformed(evt);
            }
        });

        btn_mostrar_prestamos.setText("Mostrar Prestamos");
        btn_mostrar_prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrar_prestamosActionPerformed(evt);
            }
        });

        btn_mostrar_usuarios.setText("Mostrar Usuarios");
        btn_mostrar_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrar_usuariosActionPerformed(evt);
            }
        });

        jButton1.setText("Devolver un prestamo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_crud_revista.setText("CRUD REVISTA");

        btn_crud_prestamo_profesor.setText("CRUD PRESTAMO PROFESOR");

        jButton2.setText("Pagar Multa");

        btnEditarPrestamo.setText("Editar Prestamo");
        btnEditarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPrestamoActionPerformed(evt);
            }
        });

        btnEliminarPrestamo.setText("Eliminar Prestamo");
        btnEliminarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_mostrar_material)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_crud_revista)
                                    .addComponent(btn_crud_libro))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_crud_prestamo_simple)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnEditarPrestamo))
                                    .addComponent(btn_crud_prestamo_profesor)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btn_mostrar_prestamos)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(btn_mostrar_usuarios))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPrestamo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crud_libro)
                    .addComponent(btn_crud_prestamo_simple)
                    .addComponent(btnEditarPrestamo)
                    .addComponent(btnEliminarPrestamo))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crud_revista)
                    .addComponent(btn_crud_prestamo_profesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btn_mostrar_prestamos)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btn_mostrar_usuarios)
                .addGap(12, 12, 12)
                .addComponent(btn_mostrar_material)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrar_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrar_materialActionPerformed
        // TODO add your handling code here:
        MostrarMaterial nuevo=new MostrarMaterial();
        nuevo.show();
    }//GEN-LAST:event_btn_mostrar_materialActionPerformed

    private void btn_crud_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crud_libroActionPerformed
        // TODO add your handling code here:
        CrudLibro nuevo = new CrudLibro();
        nuevo.show();
    }//GEN-LAST:event_btn_crud_libroActionPerformed

    private void btn_mostrar_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrar_usuariosActionPerformed
        // TODO add your handling code here:
        MostrarUsuarios nuevo= new MostrarUsuarios();
        nuevo.show();
    }//GEN-LAST:event_btn_mostrar_usuariosActionPerformed

    private void btn_crud_prestamo_simpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crud_prestamo_simpleActionPerformed
        // TODO add your handling code here:
        AgregarPrestamo nuevo=new AgregarPrestamo();
       nuevo.show();
    }//GEN-LAST:event_btn_crud_prestamo_simpleActionPerformed

    private void btn_mostrar_prestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrar_prestamosActionPerformed
        // TODO add your handling code here:
         MostrarPrestamos nuevo=new MostrarPrestamos();
        nuevo.show();
    }//GEN-LAST:event_btn_mostrar_prestamosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DevolverPrestamo nuevo=new DevolverPrestamo();
        nuevo.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPrestamoActionPerformed
        // TODO add your handling code here:
        EditarPrestamo nuevo=new EditarPrestamo();
        nuevo.show();
    }//GEN-LAST:event_btnEditarPrestamoActionPerformed

    private void btnEliminarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoActionPerformed
        // TODO add your handling code here:
        EliminarPrestamo nuevo=new EliminarPrestamo();
        nuevo.show();
    }//GEN-LAST:event_btnEliminarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPrestamo;
    private javax.swing.JButton btnEliminarPrestamo;
    private javax.swing.JButton btn_crud_libro;
    private javax.swing.JButton btn_crud_prestamo_profesor;
    private javax.swing.JButton btn_crud_prestamo_simple;
    private javax.swing.JButton btn_crud_revista;
    private javax.swing.JButton btn_mostrar_material;
    private javax.swing.JButton btn_mostrar_prestamos;
    private javax.swing.JButton btn_mostrar_usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
